recipe/meta.yaml
Might end up turning the Mac build off and debug locally when I can get my hands on some hardware...
=> Update to 2.16.3 & try mac build

README.md, recipe/meta.yaml
I also cleaned the recipe a little bit.
=> Rename proj4 dep

README.md, recipe/meta.yaml
Also fixed a copy-n-pasta from my last PR.
=> Test geos 351

.gitattributes, README.md, recipe/meta.yaml
Update to latest bugfix release of 2.18
=> Update to 2.18.2

LICENSE, ci_support/run_docker_build.sh, recipe/meta.yaml
=> Update icu pin

ci_support/fast_finish_ci_pr_build.sh, ci_support/run_docker_build.sh, circle.yml, recipe/meta.yaml
I forgot to merge #12 :disappointed:... so here is the next bug fix release
=> Update to v2.18.7

ci_support/fast_finish_ci_pr_build.sh, ci_support/run_docker_build.sh, circle.yml, recipe/meta.yaml
Update to bugfix version 2.18.6. Rerendering while I have my eyes on this as well
=> Update to v2.18.6

recipe/meta.yaml
Update to latest bugfix release.
=> Update to QGIS v2.18.10

recipe/meta.yaml
Merges #24 to update dependency pins, and upgrades to the latest LTR release (2.18.16)
=> v2.18.16 and update pins

recipe/meta.yaml
Attempt to update to 2.18.17. seemed to have worked locally.
=> Update to 2.18.17

README.md, recipe/meta.yaml
Checklist
Closes #49 ?
Closes #52 ?
Updated the version of QGIS and included PR #49 changes to add new maintainers.
=> Update qgis 3.4.7

README.md, recipe/meta.yaml
=> Updated LTR branch to 3.4.7

recipe/meta.yaml
=> bump to 3.4.8

recipe/meta.yaml, recipe/patches/0007-win-startDetached.patch, recipe/post-link.bat
Checklist
Bumped QGIS version to 3.6.1. Yet, I do not wish to merge this into master. I would prefer to keep this in a separate branch so people can install either the Long Term Release (currently 3.4.6) or the stable version (currently 3.6.1)
=> Update Recipe for QGIS 3.6 (stable branch)

.azure-pipelines/azure-pipelines-win.yml, recipe/meta.yaml
Checklist
Updates master (stable branch to 3.8.0
=> Update QGIS master version to 3.8.0

recipe/meta.yaml
=> Patch Update to 3.8.3

recipe/meta.yaml
=> Update LTR to 3.14.12

.azure-pipelines/azure-pipelines-win.yml, recipe/meta.yaml
=> Update master to 3.10.1

.azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_python3.6.yaml, .ci_support/linux_python3.7.yaml, .ci_support/linux_python3.8.yaml, .ci_support/osx_python3.6.yaml, .ci_support/osx_python3.7.yaml, .ci_support/osx_python3.8.yaml, .ci_support/win_c_compilervs2015cxx_compilervs2015python3.6.yaml, .ci_support/win_c_compilervs2015cxx_compilervs2015python3.7.yaml, .ci_support/win_c_compilervs2015cxx_compilervs2015python3.8.yaml, recipe/meta.yaml
=> Update to 3.12.0

.azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/win_python3.6.____cpython.yaml, .ci_support/win_python3.7.____cpython.yaml, .ci_support/win_python3.8.____cpython.yaml, README.md, recipe/meta.yaml
=> Update recipe to 3.12.1

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/osx_python3.6.____cpython.yaml, .ci_support/osx_python3.7.____cpython.yaml, .ci_support/osx_python3.8.____cpython.yaml, .scripts/build_steps.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, README.md, recipe/meta.yaml
=> Update stable to 3.14.1

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/osx_python3.6.____cpython.yaml, .ci_support/osx_python3.7.____cpython.yaml, .ci_support/osx_python3.8.____cpython.yaml, .scripts/build_steps.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, README.md, recipe/build.sh, recipe/meta.yaml
=> Update LTR to 3.10.8

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_python3.6.____cpython.yaml, .ci_support/linux_64_python3.7.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/osx_64_python3.6.____cpython.yaml, .ci_support/osx_64_python3.7.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, .ci_support/win_64_python3.6.____cpython.yaml, .ci_support/win_64_python3.7.____cpython.yaml, .ci_support/win_64_python3.8.____cpython.yaml, LICENSE.txt, README.md, azure-pipelines.yml, conda-forge.yml
@SrNetoChan we finally have a mechanism to request builds on C without having to fix that every re-render. This does not need to produce a new package BTW, and we should backport to the LTR branch.
=> Build on c

.ci_support/osx_64_python3.6.____cpython.yaml, .ci_support/osx_64_python3.7.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, recipe/meta.yaml
=> Update LTR to 3.10.10

recipe/meta.yaml, recipe/post-link.bat, recipe/test_py_qgis.py
Checklist
Changed PROJ_LIB path from `share` to `share\proj` for windows builds to fix #145
=> Changed PROJ_LIB path to share\proj 

recipe/meta.yaml, recipe/post-link.bat, recipe/test_py_qgis.py
Update LTR to 3.10.14 (Last patch release of 3.10 as LTR)
Backported the proj path fix by @jakimowb (thanks!)
Checklist
=> Backport proj fix

recipe/meta.yaml
=> Update ltr 3.16.5

README.md
Checklist
This PR add a hint to README.md that explains how to start QGIS on macOS. The hint might be removed when #183 is solved.
=> updated README.md with hint for #183

.ci_support/linux_64_python3.6.____cpython.yaml, .ci_support/linux_64_python3.7.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/migrations/geos390.yaml, .ci_support/migrations/proj720.yaml, .ci_support/osx_64_python3.6.____cpython.yaml, .ci_support/osx_64_python3.7.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/win_64_python3.6.____cpython.yaml, .ci_support/win_64_python3.7.____cpython.yaml, .ci_support/win_64_python3.8.____cpython.yaml, .ci_support/win_64_python3.9.____cpython.yaml, .scripts/build_steps.sh, .scripts/logging_utils.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, LICENSE.txt, README.md, recipe/meta.yaml
=> Update LTR to 3.16.6

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/migrations/gdal32.yaml, recipe/meta.yaml
=> Update LTR to 3.16.8

recipe/meta.yaml
=> Bump LTR to 3.16.11

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_python3.7.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/osx_64_python3.7.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/win_64_python3.7.____cpython.yaml, .ci_support/win_64_python3.8.____cpython.yaml, .ci_support/win_64_python3.9.____cpython.yaml, .gitattributes, README.md, build-locally.py, recipe/meta.yaml
=> Update LTR to 3.16.14

.azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_python3.7.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/osx_64_python3.7.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/win_64_python3.7.____cpython.yaml, .ci_support/win_64_python3.8.____cpython.yaml, .ci_support/win_64_python3.9.____cpython.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, recipe/meta.yaml
=> Update LTR branch to 3.16.16

recipe/meta.yaml
=> cleanup qtserial and qtlocation

.ci_support/linux_64_python3.10.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/osx_64_python3.10.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/win_64_python3.10.____cpython.yaml, .ci_support/win_64_python3.8.____cpython.yaml, .ci_support/win_64_python3.9.____cpython.yaml, recipe/meta.yaml
Checklist
This is intended to fix the Mac and Windows build problems in https://github.com/conda-forge/qgis-feedstock/runs/8728593385
=> pin pyqt-builder

recipe/meta.yaml
=> Update ltr 3.22.14

.ci_support/linux_64_python3.10.____cpython.yaml, .ci_support/linux_64_python3.11.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/migrations/libgdal36.yaml, .ci_support/osx_64_python3.10.____cpython.yaml, .ci_support/osx_64_python3.11.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/win_64_python3.10.____cpython.yaml, .ci_support/win_64_python3.11.____cpython.yaml, .ci_support/win_64_python3.8.____cpython.yaml, .ci_support/win_64_python3.9.____cpython.yaml, recipe/conda_build_config.yaml, recipe/meta.yaml
=> Try force gdal 3.6.1 update

recipe/meta.yaml
=> Update LTR to 3.22.15

.ci_support/linux_64_python3.10.____cpython.yaml, .ci_support/linux_64_python3.11.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/osx_64_python3.10.____cpython.yaml, .ci_support/osx_64_python3.11.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/win_64_python3.10.____cpython.yaml, .ci_support/win_64_python3.11.____cpython.yaml, .ci_support/win_64_python3.8.____cpython.yaml, .ci_support/win_64_python3.9.____cpython.yaml, recipe/meta.yaml
=> Add Openssl as host and bump 3.22.16

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_aarch64_python3.10.____cpython.yaml, .ci_support/linux_aarch64_python3.11.____cpython.yaml, .ci_support/linux_aarch64_python3.8.____cpython.yaml, .ci_support/linux_aarch64_python3.9.____cpython.yaml, .ci_support/osx_arm64_python3.10.____cpython.yaml, .ci_support/osx_arm64_python3.11.____cpython.yaml, .ci_support/osx_arm64_python3.8.____cpython.yaml, .ci_support/osx_arm64_python3.9.____cpython.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, README.md, conda-forge.yml, recipe/0003-workaround-multi-pyqt5.patch, recipe/build.sh, recipe/conda_build_config.yaml, recipe/meta.yaml
=> Update ltr 3.28.4

recipe/meta.yaml
=> Update stable version to 3.30.1

recipe/meta.yaml
=> update LTR version to 3.28.5

recipe/meta.yaml
=> Update LTR to 3.28.6

recipe/meta.yaml
=> update ltr to 3.28.8

.ci_support/linux_64_python3.10.____cpython.yaml, .ci_support/linux_64_python3.11.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/linux_aarch64_python3.10.____cpython.yaml, .ci_support/linux_aarch64_python3.11.____cpython.yaml, .ci_support/linux_aarch64_python3.8.____cpython.yaml, .ci_support/linux_aarch64_python3.9.____cpython.yaml, .ci_support/migrations/libgdal37.yaml, .ci_support/osx_64_python3.10.____cpython.yaml, .ci_support/osx_64_python3.11.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/osx_arm64_python3.10.____cpython.yaml, .ci_support/osx_arm64_python3.11.____cpython.yaml, .ci_support/osx_arm64_python3.8.____cpython.yaml, .ci_support/osx_arm64_python3.9.____cpython.yaml, .ci_support/win_64_python3.10.____cpython.yaml, .ci_support/win_64_python3.11.____cpython.yaml, .ci_support/win_64_python3.8.____cpython.yaml, .ci_support/win_64_python3.9.____cpython.yaml, recipe/meta.yaml
Checklist
See if we can fix https://github.com/conda-forge/qgis-feedstock/pull/338
=> Try manual migration to libgdal37

.azure-pipelines/azure-pipelines-win.yml, .ci_support/migrations/icu72.yaml, .ci_support/migrations/proj920.yaml, .scripts/run_osx_build.sh, recipe/0005-check-locks-not-destroyed.patch, recipe/meta.yaml, recipe/run_test.sh, recipe/test_py_qgis.py
Update LTR branch to 3.28.9
Backport fix Python  crach from main
Checklist
=> Update ltr 3.28.9

.azure-pipelines/azure-pipelines-linux.yml, recipe/meta.yaml, recipe/test_py_qgis.py
=> Try new version of pyqt-sip

recipe/meta.yaml
=> Update LTR 3.28.10

recipe/meta.yaml
Checklist
Fixes missing build number bump in https://github.com/conda-forge/qgis-feedstock/pull/386
=> bump build number and revert #386

conda-forge.yml, recipe/meta.yaml
=> add LTR back to migrations

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, azure-pipelines.yml, recipe/meta.yaml
=> update LTR to 3.34.5

.ci_support/linux_64_python3.10.____cpython.yaml, .ci_support/linux_64_python3.11.____cpython.yaml, .ci_support/linux_64_python3.12.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/linux_aarch64_python3.10.____cpython.yaml, .ci_support/linux_aarch64_python3.11.____cpython.yaml, .ci_support/linux_aarch64_python3.12.____cpython.yaml, .ci_support/linux_aarch64_python3.9.____cpython.yaml, .ci_support/migrations/libgdal39.yaml, .ci_support/migrations/libspatialindex200.yaml, .ci_support/osx_64_python3.10.____cpython.yaml, .ci_support/osx_64_python3.11.____cpython.yaml, .ci_support/osx_64_python3.12.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/osx_arm64_python3.10.____cpython.yaml, .ci_support/osx_arm64_python3.11.____cpython.yaml, .ci_support/osx_arm64_python3.12.____cpython.yaml, .ci_support/osx_arm64_python3.9.____cpython.yaml, .ci_support/win_64_python3.10.____cpython.yaml, .ci_support/win_64_python3.11.____cpython.yaml, .ci_support/win_64_python3.12.____cpython.yaml, .ci_support/win_64_python3.9.____cpython.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, recipe/meta.yaml
=> Update LTR 3.34.8

.scripts/build_steps.sh, recipe/meta.yaml
=> Update LTR 3.34.9

recipe/meta.yaml
=> Update LTR to 3.34.11

.ci_support/linux_64_python3.10.____cpython.yaml, .ci_support/linux_64_python3.11.____cpython.yaml, .ci_support/linux_64_python3.12.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/linux_aarch64_python3.10.____cpython.yaml, .ci_support/linux_aarch64_python3.11.____cpython.yaml, .ci_support/linux_aarch64_python3.12.____cpython.yaml, .ci_support/linux_aarch64_python3.9.____cpython.yaml, .ci_support/migrations/libgdal310.yaml, .ci_support/migrations/pdal282.yaml, .ci_support/osx_64_python3.10.____cpython.yaml, .ci_support/osx_64_python3.11.____cpython.yaml, .ci_support/osx_64_python3.12.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/osx_arm64_python3.10.____cpython.yaml, .ci_support/osx_arm64_python3.11.____cpython.yaml, .ci_support/osx_arm64_python3.12.____cpython.yaml, .ci_support/osx_arm64_python3.9.____cpython.yaml, .ci_support/win_64_python3.10.____cpython.yaml, .ci_support/win_64_python3.11.____cpython.yaml, .ci_support/win_64_python3.12.____cpython.yaml, .ci_support/win_64_python3.9.____cpython.yaml, recipe/meta.yaml
Checklist
Closes https://github.com/conda-forge/qgis-feedstock/pull/482 and https://github.com/conda-forge/qgis-feedstock/pull/480.
Same as https://github.com/conda-forge/qgis-feedstock/pull/484 but for the LTR branch
=> Migrate PDAL and GDAL together (LTR)

.ci_support/linux_64_python3.10.____cpython.yaml, .ci_support/linux_64_python3.11.____cpython.yaml, .ci_support/linux_64_python3.12.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/linux_aarch64_python3.10.____cpython.yaml, .ci_support/linux_aarch64_python3.11.____cpython.yaml, .ci_support/linux_aarch64_python3.12.____cpython.yaml, .ci_support/linux_aarch64_python3.9.____cpython.yaml, .ci_support/migrations/libgdal310.yaml, .ci_support/migrations/pdal282.yaml, .ci_support/osx_64_python3.10.____cpython.yaml, .ci_support/osx_64_python3.11.____cpython.yaml, .ci_support/osx_64_python3.12.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/osx_arm64_python3.10.____cpython.yaml, .ci_support/osx_arm64_python3.11.____cpython.yaml, .ci_support/osx_arm64_python3.12.____cpython.yaml, .ci_support/osx_arm64_python3.9.____cpython.yaml, .ci_support/win_64_python3.10.____cpython.yaml, .ci_support/win_64_python3.11.____cpython.yaml, .ci_support/win_64_python3.12.____cpython.yaml, .ci_support/win_64_python3.9.____cpython.yaml, recipe/meta.yaml
A working PR, unlike #483, to migrate PDAL and GDAL together due to the cycle they have in their migrations.
=> Migrate PDAL and GDAL together

.ci_support/linux_64_python3.10.____cpython.yaml, .ci_support/linux_64_python3.11.____cpython.yaml, .ci_support/linux_64_python3.12.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/linux_aarch64_python3.10.____cpython.yaml, .ci_support/linux_aarch64_python3.11.____cpython.yaml, .ci_support/linux_aarch64_python3.12.____cpython.yaml, .ci_support/linux_aarch64_python3.9.____cpython.yaml, .ci_support/migrations/qtkeychain015.yaml, .ci_support/osx_64_python3.10.____cpython.yaml, .ci_support/osx_64_python3.11.____cpython.yaml, .ci_support/osx_64_python3.12.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/osx_arm64_python3.10.____cpython.yaml, .ci_support/osx_arm64_python3.11.____cpython.yaml, .ci_support/osx_arm64_python3.12.____cpython.yaml, .ci_support/osx_arm64_python3.9.____cpython.yaml, .ci_support/win_64_python3.10.____cpython.yaml, .ci_support/win_64_python3.11.____cpython.yaml, .ci_support/win_64_python3.12.____cpython.yaml, .ci_support/win_64_python3.9.____cpython.yaml, recipe/meta.yaml
Checklist
Update LTR to 3.34.15
Replace pdal by libgdal
=> Update ltr 3.34.15

.scripts/run_docker_build.sh, build-locally.py, recipe/meta.yaml
=> Update LTR to 3.40.6
